version: "3.8"

services:
  # --- Backend API principal
  api_gestion:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: gestion-server-1
    image: gestion-server
    networks:
      - red-gane-int
    env_file:
      - ./server/.env

  # --- Frontend Astro SSR (Node)
  web_gestion:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: web_gestion
    image: web-gestion
    expose:
      - "4321"
    depends_on:
      - api_gestion
    networks:
      - red-gane-int
    env_file:
      - ./client/.env
    # Opcional: montar el .env como volumen en desarrollo
    volumes:
      - ./client/.env:/app/.env:ro

  # --- Reverse Proxy Nginx
  proxy_gestion:
    image: nginx:alpine
    container_name: proxy_gestion
    depends_on:
      - web_gestion
      - api_gestion
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8089:80"
    networks:
      - red-gane-int
    environment:
    - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}

networks:
  red-gane-int:
    external: true